version: '3.8'

services:
  latticed:
    build:
      context: ..
      dockerfile: testnet/Dockerfile
    command: ["npm", "run", "latticed"]
    ports:
      - "7777:7777"
    volumes:
      - ~/.lattice:/root/.lattice
    networks:
      - lattice-overlay

  echo-service:
    build:
      context: ..
      dockerfile: testnet/Dockerfile
    command: ["npm", "run", "services:echo"]
    networks:
      - lattice-overlay

  github-service:
    build:
      context: ..
      dockerfile: testnet/Dockerfile
    command: ["npm", "run", "services:github"]
    networks:
      - lattice-overlay

  gmail-service:
    build:
      context: ..
      dockerfile: testnet/Dockerfile
    command: ["npm", "run", "services:gmail"]
    networks:
      - lattice-overlay

networks:
  lattice-overlay:
    driver: bridge
